{{- if .Values.jxBotToken.enabled }}
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: jx-bot-token
  namespace: jx
  annotations:
    docs.jenkins-x.io: https://jenkins-x.io/v3/admin/troubleshooting/bot-token/
spec:
  runInterval: {{ .Values.jxBotToken.runInterval }}
  timeout: {{ .Values.jxBotToken.timeout }}
  podSpec:
    restartPolicy: Never  
    containers:
      - name: jx-bot-token
        image: {{ .Values.jxBotToken.image.repository }}:{{ .Values.image.tag }}
        resources:
          requests:
            cpu: 25m
            memory: 15Mi
          limits:
            cpu: 100m
        env:
        - name: OAUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: password
              name: tekton-git
        - name: GIT_PROVIDER
          value: {{ .Values.jxBotToken.gitProvider }}
    terminationGracePeriodSeconds: 60
{{- end }}