{{- if .Values.jxSecrets.enabled }}
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: jx-secrets
  annotations:
    docs.jenkins-x.io: https://jenkins-x.io/v3/admin/troubleshooting/secrets/
{{- if .Values.jxSecrets.cluster.enabled }}
  namespace: kuberhealthy
{{- end }}
spec:
  runInterval: {{ .Values.jxSecrets.runInterval }}
  timeout: {{ .Values.jxSecrets.timeout }}
  podSpec:
    securityContext:
      runAsUser: 999
      fsGroup: 999
    containers:
      - env:
          {{- if not .Values.jxSecrets.cluster.enabled }}
          - name: TARGET_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- end }}
        image: {{ .Values.jxSecrets.image.repository }}:{{ .Values.jxSecrets.image.tag }}
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
    serviceAccountName: jx-secrets-sa
---
{{- if .Values.jxSecrets.cluster.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jx-secrets-check-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jx-secrets-role
subjects:
  - kind: ServiceAccount
    name: jx-secrets-sa
    namespace: kuberhealthy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jx-secrets-role
rules:
  - apiGroups:
      - "kubernetes-client.io"
    resources:
      - externalsecrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jx-secrets-sa
  namespace: kuberhealthy
{{- end }}
{{- if not .Values.jxSecrets.cluster.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-status-role
rules:
  - apiGroups:
      - "kubernetes-client.io"
    resources:
      - externalsecrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-status-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-status-role
subjects:
  - kind: ServiceAccount
    name: pod-status-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jx-secrets-sa
{{- end }}
{{- end }}