{{- if .Values.podRestarts.enabled }}
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: pod-restarts
spec:
  runInterval: {{ .Values.podRestarts.runInterval }}
  timeout: {{ .Values.podRestarts.timeout }}
  podSpec:
    {{- if .Values.securityContext.enabled }}
    securityContext:
      runAsUser: {{ .Values.securityContext.runAsUser }}
      fsGroup: {{ .Values.securityContext.fsGroup }}
    {{- end}}
    containers:
      - env:
          {{- if not .Values.podRestarts.allNamespaces }}
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- end }}
{{- range $key, $value := .Values.podRestarts.extraEnvs }}
          - name: {{ $key }}
            value: {{ $value | quote }}
{{- end }}
        image: {{ .Values.podRestarts.image.repository }}:{{ .Values.podRestarts.image.tag }}
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: {{ .Values.podRestarts.resources.requests.cpu }}
            memory: {{ .Values.podRestarts.resources.requests.memory }}
          {{- if .Values.podRestarts.resources.limits }}
          limits:
            {{- if .Values.podRestarts.resources.limits.cpu }}
            cpu: {{ .Values.podRestarts.resources.limits.cpu }}
            {{- end }}
            {{- if .Values.podRestarts.resources.limits.memory }}
            memory: {{ .Values.podRestarts.resources.limits.memory }}
            {{- end }}
          {{- end }}
        {{- if .Values.securityContext.enabled }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
        {{- end }}
    {{- if .Values.podRestarts.nodeSelector }}
    nodeSelector:
{{- toYaml .Values.podRestarts.nodeSelector | nindent 6 }}
    {{- end }}
    {{- if .Values.podRestarts.tolerations }}
    tolerations:
{{- toYaml .Values.podRestarts.tolerations | nindent 6 }}
    {{- end }}
    restartPolicy: Never
    serviceAccountName: pod-restart-sa
---
{{- if .Values.podRestarts.allNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-status-check-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-status-role
subjects:
  - kind: ServiceAccount
    name: pod-status-sa
    namespace: kuberhealthy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-status-role
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
{{- end }}
{{- if not .Values.podRestarts.allNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-restart-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-restart-role
subjects:
  - kind: ServiceAccount
    name: pod-restart-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-restart-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-restart-sa
{{- if .Values.podRestarts.allNamespaces }}
  namespace: kuberhealthy
{{- else }}
  namespace: {{ .Release.Namespace }}
{{- end}}
{{- end }}